#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 22 21:11:41 2022

@author: q
"""

digits = '01'

def nary_tree_bfs(digits = '01', paths = [], depth = 3):    
    # paths
    paths = list(digits)
    # iterate until reach tree depth
    leafs = len(digits) ** depth
    while leafs > len(paths):
        tmpPath = paths.pop(0)
        for node in digits:
            paths += [tmpPath + node]
    # after all iterations iteration returns
    return paths

print(nary_tree_bfs(digits = '123', depth = 3))
